# .github/workflows/main.yml
name: CI for einsummable

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Clang-Format
      run: sudo apt-get install -y clang-format

    - name: Run Clang-Format
      run: clang-format -i -style=file $(find . -name '*.cc' -o -name '*.h')

    - name: Check for formatting changes
      run: git diff --exit-code