# .github/workflows/main.yml
name: CI for einsummable

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Clang-Format
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 18
        sudo ln -sf /usr/bin/clang-format-18 /usr/bin/clang-format

    - name: List Installed Binaries
      run: ls -al /usr/bin && ls -al /usr/local/bin

    - name: List Installed Binaries
      run: |
        ls -al /usr/bin
        ls -al /usr/local/bin
        ls -al /opt/llvm/bin

    - name: Find Clang-Format
      run: |
        find /usr -name clang-format*
        find /opt -name clang-format*

    - name: Display Clang-Format Version
      run: /usr/bin/clang-format --version || /opt/llvm/bin/clang-format --version || true

    - name: Run Clang-Format
      run: /usr/bin/clang-format -i -style=file $(find . -name '*.cc' -o -name '*.h') || /opt/llvm/bin/clang-format -i -style=file $(find . -name '*.cc' -o -name '*.h') || true

    - name: Show Differences
      run: git diff

    - name: Check for formatting changes
      run: git diff --exit-code