# .github/workflows/main.yml
name: CI for einsummable

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Clang-Format
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 18
        sudo ln -s /usr/bin/clang-format-18 /usr/bin/clang-format
    
    - name: Display Clang-Format Version
      run: clang-format --version

    - name: Run Clang-Format
      run: clang-format -i -style=file $(find . -name '*.cc' -o -name '*.h')

    - name: Show Differences
      run: git diff

    - name: Check for formatting changes
      run: git diff --exit-code